config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, reverse
from django.utils import timezone
from main import views, models

from .sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "articles": GenericSitemap(
        {
            "queryset": models.News.objects.filter(
                published__lte=timezone.now().date()
            ),
            "date_field": "published",
        },
        priority=0.9,
        protocol="https",
    ),
}


urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import include, path, reverse

from . import views

urlpatterns = [
    path("", views.index, name="home"),
    path("news/", views.news, name="news"),
    path("news/<str:slug>/", views.news_article, name="article"),
    path("tour/", views.tour, name="tour"),
    path("music/", views.music, name="music"),
    path("media/", views.media, name="media"),
    path("about/", views.about, name="about"),
]

main/models.py
import html

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.core.cache import cache
from django.template.defaultfilters import truncatewords
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags

from . import choices


class AboutImage(models.Model):
    description = models.CharField(max_length=255)
    image = models.ImageField()
    in_use = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "About Page Images"

    def save(self, *args, **kwargs):
        if self.in_use:
            try:
                temp = AboutImage.objects.get(in_use=True)
                if self != temp:
                    temp.in_use = False
                    temp.save()
            except AboutImage.DoesNotExist:
                pass
        cache.clear()
        super().save(*args, **kwargs)


class AboutText(models.Model):
    content = RichTextField()
    in_use = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "About Page Text"

    def save(self, *args, **kwargs):
        if self.in_use:
            try:
                temp = AboutText.objects.get(in_use=True)
                if self != temp:
                    temp.in_use = False
                    temp.save()
            except AboutText.DoesNotExist:
                pass
        cache.clear()
        super().save(*args, **kwargs)

    @property
    def content_preview(self):
        return f"{strip_tags(html.unescape(self.content[:150]))} . . ."


class AboutVideo(models.Model):
    description = models.CharField(max_length=255)
    embed_html = models.TextField()
    in_use = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "About Page Videos"

    def save(self, *args, **kwargs):
        if self.in_use:
            try:
                temp = AboutVideo.objects.get(in_use=True)
                if self != temp:
                    temp.in_use = False
                    temp.save()
            except AboutVideo.DoesNotExist:
                pass
        cache.clear()
        super().save(*args, **kwargs)


class Banner(models.Model):
    text = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    in_use = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.in_use:
            try:
                temp = Banner.objects.get(in_use=True)
                if self != temp:
                    temp.in_use = False
                    temp.save()
            except Banner.DoesNotExist:
                pass
        cache.clear()
        super().save(*args, **kwargs)


class Event(models.Model):
    date = models.DateField()
    time = models.TimeField()
    venue = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=choices.STATES, default="ID")
    cover = models.PositiveIntegerField(null=True, blank=True)
    age_restrictions = models.CharField(
        max_length=2, choices=choices.RESTRICTIONS, default="AA"
    )

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)

    @property
    def location(self):
        return f"{self.city}, {self.state}"


class Inquiry(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    received = models.DateTimeField(default=timezone.now)
    seen = models.BooleanField(default=False)
    responded_to = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Inquiries"

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)


class Media(models.Model):
    description = models.CharField(max_length=255)
    image = models.ImageField()

    class Meta:
        verbose_name_plural = "Media Page Images"

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)


class Music(models.Model):
    title = models.CharField(max_length=255)
    embed_html = models.TextField()

    class Meta:
        verbose_name_plural = "Embedded Albums"

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)


class News(models.Model):
    image = models.ImageField(null=True)
    title = models.CharField(max_length=255)
    content = RichTextUploadingField()
    published = models.DateField()
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "News Posts"

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)

    @property
    def preview(self):
        return truncatewords(strip_tags(html.unescape(self.content)), 50)[:-1]

    def get_absolute_url(self):
        return reverse("article", kwargs={"slug": self.slug})


class Press(models.Model):
    source = models.CharField(max_length=255)
    image = models.ImageField()
    content = models.TextField()
    link = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Press"

    def save(self, *args, **kwargs):
        cache.clear()
        super().save(*args, **kwargs)

main/forms.py
from django import forms

from . import models


class InquiryForm(forms.ModelForm):
    class Meta:
        model = models.Inquiry
        fields = ("name", "email", "message")

main/views.py
from django import http
from django.shortcuts import render
from django.utils import timezone

from . import forms, models


def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


def index(request):
    banner = get_or_none(models.Banner, in_use=True)
    current_date = timezone.localtime().date()
    news = models.News.objects.filter(published__lte=current_date).order_by(
        "-published"
    )[:3]
    events = models.Event.objects.all().order_by("-date")[:3]
    if request.is_ajax():
        print("Request == Ajax")
        form = forms.InquiryForm(request.POST)
        if form.is_valid():
            form.save()
            return http.HttpResponse(status=200)
        return http.HttpResponse(status=400)
    return render(
        request, "main/index.html", {"banner": banner, "news": news, "events": events}
    )


def news(request):
    banner = get_or_none(models.Banner, in_use=True)
    current_date = timezone.localtime().date()
    news = models.News.objects.filter(published__lte=current_date).order_by(
        "-published"
    )
    return render(request, "main/news.html", {"banner": banner, "news": news})


def news_article(request, slug):
    banner = get_or_none(models.Banner, in_use=True)
    article = models.News.objects.get(slug=slug)
    return render(
        request, "main/news-article.html", {"banner": banner, "article": article}
    )


def tour(request):
    banner = get_or_none(models.Banner, in_use=True)
    events = models.Event.objects.all().order_by("-date")
    return render(request, "main/tour.html", {"banner": banner, "events": events})


def music(request):
    banner = get_or_none(models.Banner, in_use=True)
    music = models.Music.objects.all()
    return render(request, "main/music.html", {"banner": banner, "music": music})


def media(request):
    banner = get_or_none(models.Banner, in_use=True)
    media = models.Media.objects.all()
    return render(request, "main/media.html", {"banner": banner, "media": media})


def about(request):
    banner = get_or_none(models.Banner, in_use=True)
    image = get_or_none(models.AboutImage, in_use=True)
    text = get_or_none(models.AboutText, in_use=True)
    video = get_or_none(models.AboutVideo, in_use=True)
    return render(
        request,
        "main/about.html",
        {"banner": banner, "image": image, "text": text, "video": video},
    )

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
About // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
    .heading {
        height: unset;
    }
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">About</h1>
    {% include "partials/nav.html" %}
</section>

<section class="about">
    <img class="about__img" src="/media/{{ image.image }}" alt="{{ image.description }}" />
    <div class="about__text">
        {% autoescape off %}
            {{ text.content }}
        {% endautoescape off %}
    </div>
    <div class="about__video">
        {% autoescape off %}
            {{ video.embed_html }}
        {% endautoescape %}
    </div>
</section>

<section class="press">
<section>
{% endblock content %}

{% block page-scripts %}
{% endblock page-scripts %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-grid %}
grid-template-columns: 100%;
grid-template-rows: 100vh 1fr 0.6fr 0.5fr;
{% endblock page-grid %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <img class="heading__image" src={% static "img/hero.png" %} alt="Sick Wish promotional photo" />
    <h1 class="heading__title">SICK WISH</h1>
    {% include "partials/nav_index.html" %}
</section>

<section class="news-preview">
    <h3 class="news-preview__header">News</h3>
    {% for post in news %}
        <div class="news-preview__post">
            <div class="news-preview__image">
                <img src="/media/{{ post.image }}" />
            </div>
            <h4 class="news-preview__title">{{ post.title }}</h4>
            <p class="news-preview__date">{{ post.published }}</p>
            <p class="news-preview__content">{{ post.preview }} . . .</p>
            <a href="/news/{{ post.slug }}" class="news-preview__link bordered">
                Read More
                <svg class="chevron chevron--right" viewBox="0 0 4 4" version="1.1" xmlns="http://www.w3.org/2000/svg">
                    <path d="M 0,0 L 4,0 L 4,4" fill="none" stroke="#fff" strokeWidth="10" />
                </svg>
            </a>
        </div>
    {% endfor %}
    <a href="/news" class="news-preview__cta">View All</a>
</section>

<section class="tour tour--index">
    <h3 class="tour__header">Tour</h3>
    {% for event in events %}
        <div class="tour__event">
            <h5 class="tour__location">{{ event.location }}</h5>
            <p class="tour__date">{{ event.date }}</p>
            <p class="tour__venue"><span class="grey">@</span> {{ event.venue }}</p>
            <p class="tour__details grey">{{ event.time }} | {% if event.cover %} ${{ event.cover }} {% else %} Free {% endif %}</p>
            <p class="tour__restrictions grey">{{ event.get_age_restrictions_display }}</p>
        </div>
    {% endfor %}
    <a href="/tour" class="tour__cta">View All</a>
</section>

<section id="contact" class="contact bordered">
    <h3 class="contact__title">Contact Us</h3>
    <form class="contact__form" method="post">
        <div id="name" class="form__field">
            <span class="form__field_innerwrapper">
                <label id="name-label" for="name">Name</label>
                <input type="text" name="name" onfocus="handleFocus(this.name);" onblur="handleBlur(this.name);" onchange="handleChange(this);" />
            </span>
        </div>
        <div id="email" class="form__field">
            <span class="form__field_innerwrapper">
                <label id="email-label" for="email">Email</label>
                <input type="email" name="email" onfocus="handleFocus(this.name);" onblur="handleBlur(this.name);" onchange="handleChange(this);" />
            </span>
        </div>
        <div id="message" class="form__field form__field--textarea">
            <span class="form__field_innerwrapper">
                <label id="message-label" for="message">Message</label>
                <textarea name="message" onfocus="handleFocus(this.name);" onblur="handleBlur(this.name);" onchange="handleChange(this);"></textarea>
            </span>
        </div>
        {% csrf_token %}
        <input class="btn" type="submit" value="Submit" />
        <span class="response"></span>
    </form>
</section>
{% endblock content %}

{% block page-scripts %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/formfields.js' %}"></script>
<script>
function populateResponse(success, message) {
    textWrapper = $('.response')[0]
    textWrapper.setAttribute("class", "response");
    textWrapper.innerText = message;
    if (!success) {
        textWrapper.classList.add("response--error");
    }
}

function clearForm() {
    $(".contact__form")[0].reset()
    $("#name")[0].classList.remove("form__field--active");
    $("#email")[0].classList.remove("form__field--active");
    $("#message")[0].classList.remove("form__field--active");
}

$(".contact__form").on("submit", function(event) {
  event.preventDefault();
  $.ajax({
    type: "POST",
    url: "{{ request.path }}",
    data: values,
    success: function(response) {
        populateResponse(true, "Thank you");
        clearForm();
    },
    error: function(response) {
        populateResponse(false, "An error occurred");
    }
  });
});
</script>
{% endblock page-scripts %}

main/templates/main/media.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}
{% load thumbnail %}

{% block page-title %}
Media // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
    .heading {
        height: unset;
    }
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">Media</h1>
    {% include "partials/nav.html" %}
</section>

<section class="gallery">
    <div class="gallery__active-container">
        <p class="gallery__chevron" onClick="previousPhoto()">&#8249;</p>
        <img class="gallery__photo--active" src="/media/{{ media.0.image }}" alt="{{ media.0.description }}" onClick="nextPhoto()" />
        <p class="gallery__chevron" onClick="nextPhoto()">&#8250;</p>
    </div>
    <div class="gallery__preview">
        {% for image in media %}
            <img
                id="{{ image.id }}"
                class="gallery__photo {% if forloop.first %}gallery__photo--highlight{% endif %}"
                src="{{ image.image|thumbnail_url:'preview' }}"
                alt="{{ image.description }}"
                onClick="changeActivePhoto(this);"
            />
        {% endfor %}
    </div>
</section>
{% endblock content %}

{% block page-scripts %}
<script>
    document.onkeydown = checkKey;

    var photoCount = document.getElementsByClassName("gallery__photo").length;
    var activePhoto = document.getElementsByClassName("gallery__photo--active")[0];
    var activePhotoId = 1;

    function changeActivePhoto(element){
        let oldPhoto = document.getElementById(activePhotoId)

        oldPhoto.classList.remove("gallery__photo--highlight");
        element.classList.add("gallery__photo--highlight");

        activePhoto.src = getFullPhoto(element.src);
        activePhoto.alt = element.alt;
        activePhotoId = parseInt(element.id);
    }

    function nextPhoto() {
        if (activePhotoId < photoCount) {
            let newPhoto = document.getElementById(activePhotoId + 1)
            let oldPhoto = document.getElementById(activePhotoId)

            newPhoto.classList.add("gallery__photo--highlight");
            oldPhoto.classList.remove("gallery__photo--highlight");

            activePhoto.src = getFullPhoto(newPhoto.src);
            activePhoto.alt = newPhoto.alt;
            activePhotoId = parseInt(newPhoto.id);
        } else {
            let newPhoto = document.getElementById(1)
            let oldPhoto = document.getElementById(activePhotoId)

            newPhoto.classList.add("gallery__photo--highlight");
            oldPhoto.classList.remove("gallery__photo--highlight");

            activePhoto.src = getFullPhoto(newPhoto.src);
            activePhoto.alt = newPhoto.alt;
            activePhotoId = parseInt(newPhoto.id);
        }
    }

    function previousPhoto() {
        if (activePhotoId > 1) {
            let newPhoto = document.getElementById(activePhotoId - 1)
            let oldPhoto = document.getElementById(activePhotoId)

            newPhoto.classList.add("gallery__photo--highlight");
            oldPhoto.classList.remove("gallery__photo--highlight");

            activePhoto.src = getFullPhoto(newPhoto.src);
            activePhoto.alt = newPhoto.alt;
            activePhotoId = parseInt(newPhoto.id);
        } else {
            let newPhoto = document.getElementById(photoCount)
            let oldPhoto = document.getElementById(activePhotoId)

            newPhoto.classList.add("gallery__photo--highlight");
            oldPhoto.classList.remove("gallery__photo--highlight");

            activePhoto.src = getFullPhoto(newPhoto.src);
            activePhoto.alt = newPhoto.alt;
            activePhotoId = parseInt(newPhoto.id);
        }
    }

    function getFullPhoto(src) {
        return src.substr(0, src.indexOf(".25x25"));
    }

    function checkKey(e) {
        var event = window.event ? window.event : e;
        if (event.keyCode == 39) {
            nextPhoto();
        } else if (event.keyCode == 37) {
            previousPhoto();
        }
    }

</script>
{% endblock page-scripts %}

main/templates/main/music.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
Music // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-grid %}
grid-template-columns: 100%;
{% endblock page-grid %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
    .heading {
        height: unset;
    }
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">Music</h1>
    {% include "partials/nav.html" %}
</section>

<section class="music">
    {% for embed in music %}
        <div class="music__embed">
            {% autoescape off %}
                {{ embed.embed_html }}
            {% endautoescape %}
        </div>
    {% endfor %}
</section>
{% endblock content %}

{% block page-scripts %}
{% endblock page-scripts %}

main/templates/main/news-article.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
{{ article.title }} // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-grid %}
grid-template-columns: 100%;
{% endblock page-grid %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
    .heading {
        height: unset;
    }
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">News</h1>
    {% include "partials/nav.html" %}
</section>

<section class="news-article">
    <div class="news-article__image">
        <img src="/media/{{ article.image }}" />
    </div>
    <h4 class="news-article__title">{{ article.title }}</h4>
    <p class="news-article__date">{{ article.published }}</p>
    <div class="news-article__content">
        {% autoescape off %}
            {{ article.content }}
        {% endautoescape %}
    </div>
</section>
{% endblock content %}

{% block page-scripts %}
{% endblock page-scripts %}

main/templates/main/news.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
News // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-grid %}
grid-template-columns: 100%;
{% endblock page-grid %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
@media only screen and (min-width: 768px) {
    body {
        grid-template-rows: 40vh 1fr;
    }

    .news-preview {
        margin-top: 0;
    }

    .heading {
        height: unset;
    }
}
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">News</h1>
    {% include "partials/nav.html" %}
</section>

<section class="news-preview">
    {% for post in news %}
        <div class="news-preview__post">
            <div class="news-preview__image">
                <img src="/media/{{ post.image }}" />
            </div>
            <h4 class="news-preview__title">{{ post.title }}</h4>
            <p class="news-preview__date">{{ post.published }}</p>
            <p class="news-preview__content">{{ post.preview }} . . .</p>
            <a href="/news/{{ post.slug }}" class="news-preview__link bordered">
                Read More
                <svg class="chevron chevron--right" viewBox="0 0 4 4" version="1.1" xmlns="http://www.w3.org/2000/svg">
                    <path d="M 0,0 L 4,0 L 4,4" fill="none" stroke="#fff" strokeWidth="10" />
                </svg>
            </a>
        </div>
    {% endfor %}
</section>
{% endblock content %}

{% block page-scripts %}
{% endblock page-scripts %}

main/templates/main/tour.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block page-title %}
Tour // Sick Wish
{% endblock page-title %}

{% block page-description %}
Sick Wish is a New(er) Wave band formed in Boise, ID in 2014 by former Built to Spill bassist Brett Nelson, his son Jonah Nelson, and local musicians Edward Dunn and Craig Macomb.
{% endblock page-description %}

{% block page-grid %}
grid-template-columns: 100%;
{% endblock page-grid %}

{% block page-styles %}
<link rel="stylesheet" href="{% sass_src 'css/main.scss' %}" type="text/css">
<style>
    .heading {
        height: unset;
    }

    .tour {
        margin: 0;
    }
</style>
{% endblock page-styles %}

{% block content %}
<section class="heading">
    <h1 class="heading__title heading__title--child">Tour</h1>
    {% include "partials/nav.html" %}
</section>

<section class="tour">
    {% for event in events %}
        <div class="tour__event">
            <h5 class="tour__location">{{ event.location }}</h5>
            <p class="tour__date">{{ event.date }}</p>
            <p class="tour__venue"><span class="grey">@</span> {{ event.venue }}</p>
            <p class="tour__details grey">{{ event.time }} | {% if event.cover %} ${{ event.cover }} {% else %} Free {% endif %}</p>
            <p class="tour__restrictions grey">{{ event.get_age_restrictions_display }}</p>
        </div>
    {% endfor %}
</section>
{% endblock content %}

{% block page-scripts %}
{% endblock page-scripts %}